name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Build for linux/amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -o bin/webdav-cloner-linux-amd64 ./cmd/webdav-cloner

    - name: Build for linux/arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o bin/webdav-cloner-linux-arm64 ./cmd/webdav-cloner

    - name: Build for windows/amd64
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -v -o bin/webdav-cloner-windows-amd64.exe ./cmd/webdav-cloner

    - name: Build for darwin/amd64
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -v -o bin/webdav-cloner-darwin-amd64 ./cmd/webdav-cloner

    - name: Build for darwin/arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -v -o bin/webdav-cloner-darwin-arm64 ./cmd/webdav-cloner

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/webdav-cloner-linux-amd64
          bin/webdav-cloner-linux-arm64
          bin/webdav-cloner-windows-amd64.exe
          bin/webdav-cloner-darwin-amd64
          bin/webdav-cloner-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true
